services:
  - type: web
    name: yarngpt-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
    disk:
      name: yarngpt-data
      mountPath: /data
      sizeGB: 2